name: Deploy React App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3    # ✅ Use v3 for latest stability and speed

    - name: Set up Node.js
      uses: actions/setup-node@v3  # ✅ Use v3 for consistency
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci                  # ✅ Faster and cleaner for CI/CD than `npm install`

    - name: Build React app
      run: npm run build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: siteprep-webapp-dev
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: ./build
